config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'top', to: 'diaries#top'
  devise_for :users

  root 'diaries#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  resources :diaries do
    resources :comments
    collection do
      post :confirm
      get :search
      get :ranking
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poses, :only => [:index, :show] do
    collection do
      get :auto_complete
    end
  end

  resources :admin, :only => [:index]

  namespace :admin do
    resources :users
    resources :poses
    resources :effects
    resources :tags
    resources :requests
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]
  resources :events do
    collection do
      post :confirm
    end
  end
  resources :requests, only: [:new, :create]
end

app/views/admin/index.html.erb
<%= javascript_include_tag 'link.js' %>
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.request_body') %></h5>

  <table class="table table-hover table-sm">
    <tbody>
      <% @requests.each do |request| %>
        <tr data-link="<%= admin_request_path(request) %>" style="cursor: pointer;">
          <td><%= request.body %></td>
          <td><%= request.user.name %></td>
          <td><%= request.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div align="center">
    <%= link_to '要望一覧へ', admin_requests_path, class: "btn indigo accent-1 btn-sm" %>
  </div>

  <p style="margin: 20px">&nbsp;</p>

  <div class="row">
    <div class="w-50">
      <h5 class="h5-responsive" align="center"><%= t('view.pose') %></h5>
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th><%= t('view.pose_name') %></th>
            <th><%= t('view.pose_name_sans') %></th>
          </tr>
        </thead>

        <tbody>
          <% @poses.each do |pose| %>
            <tr data-link="<%= admin_pose_path(pose) %>" style="cursor: pointer;">
              <td><%= pose.name %></td>
              <td><%= pose.sans_name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div align="right">
        <%= link_to 'ポーズ一覧へ', admin_poses_path, class: "btn indigo accent-1 btn-sm" %>
      </div>
    </div>

    <div class="w-50">
      <h5 class="h5-responsive" align="center"><%= t('view.user') %></h5>
      <table class="table table-hover table-sm">
        <thead>
          <tr>
            <th><%= t('view.user') %></th>
            <th><%= t('view.email') %></th>
            <th><%= t('view.admin') %></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr data-link="<%= admin_user_path(user) %>" style="cursor: pointer;">
              <td><%= user.name %></td>
              <td><%= user.email %></td>
              <td><%= human_boolean(user.admin) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div align="right">
        <%= link_to 'ユーザ一覧へ', admin_users_path, class: "btn indigo accent-1 btn-sm" %>
      </div>

    </div>
  </div>

  <p style="margin: 20px">&nbsp;</p>

  <div class="row">
    <div class="w-50">
      <h5 class="h5-responsive" align="center"><%= t('view.effect') %></h5>
      <table class="table table-hover table-sm">
        <tbody>
          <% @effects.each do |effect| %>
            <tr data-link="<%= edit_admin_effect_path(effect) %>" style="cursor: pointer;">
              <td><%= effect.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div align="right">
        <%= link_to '効果一覧へ', admin_effects_path, class: "btn indigo accent-1 btn-sm" %>
      </div>
    </div>

    <div class="w-50">
      <h5 class="h5-responsive" align="center"><%= t('view.tag') %></h5>
      <table class="table table-hover table-sm">

        <tbody>
          <% @tags.each do |tag| %>
            <tr data-link="<%= edit_admin_tag_path(tag) %>" style="cursor: pointer;">
              <td><%= tag.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div align="right">
        <%= link_to 'タグ一覧へ', admin_tags_path, class: "btn indigo accent-1 btn-sm" %>
      </div>
    </div>
  </div>
</div>