config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'top', to: 'diaries#top'
  devise_for :users

  root 'diaries#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  resources :diaries do
    resources :comments
    collection do
      post :confirm
      get :search
      get :ranking
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poses, :only => [:index, :show] do
    collection do
      get :auto_complete
    end
  end

  resources :admin, :only => [:index]

  namespace :admin do
    resources :users
    resources :poses
    resources :effects
    resources :tags
    resources :requests
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]
  resources :events do
    collection do
      post :confirm
    end
  end
  resources :requests, only: [:new, :create]
end

app/models/event.rb
class Event < ApplicationRecord
  validates_datetime :hold_date, :on_or_after => lambda { Date.today }
  
  validates :name, presence: true
  validates :place, presence: true

  belongs_to :user
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :prohibit_editing, only: [:edit, :destroy]

  def index
    @events = Event.all.page(params[:page]).per(10)
    @q = Event.ransack(params[:q])
    @events = @q.result.order(hold_date: :desc)
    if params[:all_events]
      @events = @events.page(params[:page]).per(10)
    else
      @events = @events.page(params[:page]).per(10).where('hold_date >= ?', Time.now)
    end
  end

  def new
    if params[:back]
      @event = Event.new(event_params)
    else
      @event = Event.new
    end
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    if @event.save
      redirect_to events_path, notice: 'イベントを作成しました!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to events_path, notice: 'イベントを編集しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: 'イベントを削除しました！'
  end

  def confirm
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    render :new if @event.invalid?
  end

  private

  def event_params
    params.require(:event).permit(:name, :user_id, :hold_date, :place, :url, :detail)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def prohibit_editing
    if @event.user != current_user
      redirect_to event_path(@event), notice: '自分以外が投稿したイベントを編集することは出来ません'
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def choose_new_or_edit_event
    if action_name == 'new' || action_name == 'confirm'
      confirm_events_path
    elsif action_name == 'edit'
      event_path
    end
  end
end

app/views/events/_form.html.erb
<%= form_with(model: @event, local: true, url: choose_new_or_edit_event ) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h5 class="h5-responsive"><%= pluralize(@event.errors.count, "つのエラー") %> が存在しているため、保存出来ません:</h5>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :hold_date %>
    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
      <%= form.text_field :hold_date, id: :event_hold_date, class: "form-control datetimepicker-input", data: { target: '#event_hold_date'}, placeholder: "年/月/日 時:分"%>
      <div class="input-group-append" data-target="#event_hold_date" data-toggle="datetimepicker">
        <div class="input-group-text"><i class="fa fa-calendar"></i></div>
      </div>
     </div>
   </div>
   <script type="text/javascript">
     $(function () {
          $('#event_hold_date').datetimepicker({
            autoclose: true,
            sideBySide: true
                });
     });
   </script>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :detail %>
    <%= form.text_area :detail, id: :event_detail, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :place %>
    <%= form.text_field :place, id: :event_place, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :url %>
    <%= form.url_field :url, id: :event_url, class: "form-control", placeholder: "https://" %>
  </div><br>

  <div class="actions" align="center">
    <%= form.submit class: "btn indigo accent-1 mr-3" %>
    <%= link_to '戻る', events_path, class: "btn purple lighten-4" %>
  </div>
<% end %>

app/views/events/confirm.html.erb
<div class="container">

  <%= form_with(model: @event, local: true) do |form| %>
    <%= form.hidden_field :user_id %>
    <%= form.hidden_field :hold_date %>
    <%= form.hidden_field :name %>
    <%= form.hidden_field :detail %>
    <%= form.hidden_field :place %>
    <%= form.hidden_field :url %>

    <div class="col-12">
      <table class="table" width="100%">
        <tr>
          <td><%= t('view.event_hold_date') %></td>
          <td><%= @event.hold_date.to_s(:event_date) %></td>
        </tr>

        <tr>
          <td><%= t('view.event_name') %></td>
          <td><%= @event.name %></td>
        </tr>

        <tr>
          <td><%= t('view.event_detail') %></td>
          <td><%= @event.detail %></td>
        </tr>

        <tr>
          <td><%= t('view.event_place') %></td>
          <td><%= @event.place %></td>
        </tr>

        <tr>
          <td><%= t('view.event_url') %></td>
          <td><%= link_to @event.url, @event.url, target: "_blank" %></td>
        </tr>

        <tr>
          <td colspan="2" align="center"><%= form.submit "投稿する", class: "btn indigo accent-1" %>
            <%= form.submit "戻る", name: "back", class: "btn purple lighten-4" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.event') %>を編集</h5>
  <%= render 'form', event: @event %>
</div>

app/views/events/index.html.erb
<%= javascript_include_tag 'link.js' %>
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.event') %><%= t('view.index') %></h5>

  <p class="m-4"></p>

  <%= search_form_for @q, url: events_path do |f| %>
    <div class="form-inline">
      <%= check_box_tag :all_events, class: "form-check-input" %>&nbsp;
      <%= f.label :all_events, "完了済のイベントも表示する", class: "form-check-label" %>
      <span class="pr-5"></span><%= f.submit "表示", class: "btn purple lighten-4 btn-sm" %>
    </div>
  <% end %>
  
  <p class="m-4"></p>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('view.event_hold_date') %></th>
        <th><%= t('view.event_name') %></th>
        <th><%= t('view.event_place') %></th>
        <th><%= t('view.event_user') %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr data-link="<%= event_path(event) %>" style="cursor: pointer;">
          <td><%= event.hold_date.to_s(:event_date) %></td>
          <td><%= event.name %></td>
          <td><%= event.place %></td>
          <td><%= event.user.name %></td>
          <% if event.user == current_user %>
            <td><%= link_to '編集', edit_event_path(event) %></td>
            <td><%= link_to '削除', event_path(event), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
          <% else %>
            <td colspan="2"></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table><br>

  <div align="center">
    <%= link_to 'イベント新規作成', new_event_path, class: "btn indigo accent-1	" %>
    <%= link_to '戻る', root_path, class: "btn purple lighten-4" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.event') %>を追加する</h5>
  <p class="m-2">&nbsp;</p>
  <%= render 'form', event: @event %>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="col-12">
    <table class="table" width="100%">
      <tr>
        <th><%= t('view.event_hold_date') %></th>
        <td><%= @event.hold_date.to_s(:event_date) %></td>
      </tr>

      <tr>
        <th><%= t('view.event_name') %></th>
        <td><%= @event.name %></td>
      </tr>

      <tr>
        <th><%= t('view.event_detail') %></th>
        <td><%= @event.detail %></td>
      </tr>

      <tr>
        <th><%= t('view.event_place') %></th>
        <td><%= @event.place %></td>
      </tr>

      <tr>
        <th><%= t('view.event_url') %></th>
        <td>
          <%= link_to @event.url, @event.url, target: "_blank" %>
        </td>
      </tr>

      <tr>
        <th><%= t('view.event_user') %></th>
        <td><%= link_to @event.user.name, user_path(@event.user) %></td>
      </tr>

      <% if @event.user == current_user %>
      <tr>
        <td colspan="2" align="center">
            <%= link_to '編集', event_path(@event), class: "btn indigo accent-1 mr-3" %>
            <%= link_to '削除', event_path(@event), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-outline-danger mr-3" %>
        </td>
      </tr>
      <% end %>
    </table>
    <div align="center">
      <%= link_to '戻る', events_path, class: "btn purple lighten-4" %>
    </div>
  </div>
</div>