config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'top', to: 'diaries#top'
  devise_for :users

  root 'diaries#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  resources :diaries do
    resources :comments
    collection do
      post :confirm
      get :search
      get :ranking
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poses, :only => [:index, :show] do
    collection do
      get :auto_complete
    end
  end

  resources :admin, :only => [:index]

  namespace :admin do
    resources :users
    resources :poses
    resources :effects
    resources :tags
    resources :requests
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]
  resources :events do
    collection do
      post :confirm
    end
  end
  resources :requests, only: [:new, :create]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy, foreign_key: 'tag_id'
  has_many :diaries, through: :taggings, source: :tag

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :admin_flg

  def index
    @tags = Tag.all.page(params[:page]).per(10)
  end

  def new
    if params[:back]
      @tag = Tag.new(tag_params)
    else
      @tag = Tag.new
    end
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to admin_tags_path, notice: 'タグを作成しました!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @tag.update(tag_params)
      redirect_to admin_tags_path, notice: 'タグを編集しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @tag.destroy
    redirect_to admin_tags_path, notice: 'タグを削除しました！'
  end

  private

  def tag_params
    params.require(:tag).permit(:name, diary_ids: [])
  end

  def set_tag
    @tag = Tag.find(params[:id])
  end
end

app/views/admin/tags/edit.html.erb
<div class="container">

  <h5 class="h5-responsive" align="center"><%= t('view.tag') %>を編集</h5>
  <%= form_with(model: @tag, url: admin_tag_path, local: true ) do |form| %>
     <% if @tag.errors.any? %>
      <div id="error_explanation">
        <h5 class="h5-responsive"><%= pluralize(@tag.errors.count, "つのエラー") %> が存在しているため、保存出来ません:</h5>
        <ul>
          <% @tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_field :name, id: :tag_name, class: "form-control" %>
    </div><br>

    <div class="actions" align="center">
      <%= form.submit class: "btn indigo accent-1 mr-3" %>
      <%= link_to '削除', admin_tag_path(@tag), method: :delete, data: { confirm: '本当に削除しますか?' }, class: "btn btn-outline-danger mr-3" %>
    </div>
  <% end %>

  <p class="m-5"></p>

  <div align="center">
    <%= link_to '戻る', admin_tags_path, class: "btn purple lighten-4" %>
  </div>
</div>

app/views/admin/tags/index.html.erb
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.tag') %><%= t('view.index') %></h5>
  <div align="right">
    <%= link_to 'タグ新規作成', new_admin_tag_path, class: "btn indigo accent-1 mr-3"  %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('view.tag') %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><%= link_to '編集', edit_admin_tag_path(tag) %></td>
          <td><%= link_to '削除', admin_tag_path(tag), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @tags %>

  <p class="m-5"></p>

  <div align="center">
    <%= link_to '戻る', admin_index_path, class: "btn purple lighten-4" %>
  </div>
</div>

app/views/admin/tags/new.html.erb
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.tag') %>を追加する</h5>

  <%= form_with(model: @tag, url: admin_tags_path, local: true ) do |form| %>
    <% if @tag.errors.any? %>
      <div id="error_explanation">
        <h5 class="h5-responsive"><%= pluralize(@tag.errors.count, "つのエラー") %> が存在しているため、保存出来ません:</h5>
        <ul>
          <% @tag.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.text_field :name, id: :tag_name, class: "form-control" %>
    </div><br>

    <div class="actions" align="center">
      <%= form.submit class: "btn indigo accent-1 mr-3" %>
      <%= link_to '戻る', admin_index_path, class: "btn purple lighten-4" %>
    </div>
  <% end %>
</div>