config/routes.rb
Rails.application.routes.draw do

  get 'relationships/create'
  get 'relationships/destroy'
  get 'top', to: 'diaries#top'
  devise_for :users

  root 'diaries#index'

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :follow
    end
  end

  resources :diaries do
    resources :comments
    collection do
      post :confirm
      get :search
      get :ranking
    end
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :poses, :only => [:index, :show] do
    collection do
      get :auto_complete
    end
  end

  resources :admin, :only => [:index]

  namespace :admin do
    resources :users
    resources :poses
    resources :effects
    resources :tags
    resources :requests
  end

  resources :conversations do
    resources :messages
  end

  resources :relationships, only: [:create, :destroy]
  resources :events do
    collection do
      post :confirm
    end
  end
  resources :requests, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  include FriendlyId
  friendly_id :name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :diaries, dependent: :destroy

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :requests, dependent: :destroy

  validates :name, presence: true, length: { maximum: 64 },
                    format: { with: /\A[a-zA-Z0-9]+\z/ },
                    uniqueness: true

  mount_uploader :avatar, AvatarUploader

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    clean_up_passwords
    update_attributes(params, *options)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_flg

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def new
    if params[:back]
      @user = User.new(user_params)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'ユーザを作成しました!'
    else
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    @user.skip_confirmation!
    if @user.update_without_current_password(user_params)
      redirect_to admin_user_path(@user), notice: 'ユーザを編集しました！'
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice: 'ユーザを削除しました！'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :admin, :avatar_cache,
                                 :confirmed_at, :remove_avatar, :password)
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def destroy_self
    if @user == current_user
      redirect_to admin_users_path, notice: '自身を削除することは出来ません'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :follow]
  before_action :authenticate_user!

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました！'
    elsif @user.update_without_current_password(user_params)
      redirect_to user_path(@user), notice: 'プロフィールを更新しました！'
    else
      redirect_to edit_user_path(@user.id), notice: 'お名前には英数字のみ利用可能です'
    end
  end

  def follow
    @following = User.find(@user.following_ids)
    @followers = User.find(@user.follower_ids)
    render 'follow'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :avatar, :remove_avatar, :password, :avatar_cache)
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/views/admin/users/edit.html.erb
<div class="container">
  <h5 class="h5-responsive"><%= t('view.user') %>を編集</h5>

  <%= form_with(model: @user, url: admin_user_path, local: true ) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h5 class="h5-responsive"><%= pluralize(@user.errors.count, "つのエラー") %> が存在しているため、保存出来ません:</h5>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>&nbsp;<em><font size="-1">(英数字のみ利用可能です)</font></em>
      <%= form.text_field :name, id: :user_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, id: :user_password, class: "form-control" %>
    </div>

    <div class="form-inline">
      <div class="form-group">
        <%= form.label :avatar %>
        <%= image_tag(@user.avatar_url) if @user.avatar && @user.avatar.url %>
        <%= form.file_field :avatar, class: "form-control-file" %>
        <%= form.hidden_field :avatar_cache %>
      </div>

      <% if @user.avatar && @user.avatar.url %>
        <div class="form-group">
          <%= form.check_box :remove_avatar, id: :user_remove_avatar, class: "form-check-input" %>
          <%= form.label :remove_avatar, class: "form-check-label" %>
        </div>
      <% end %>
    </div><br>

    <div class="form-check">
      <%= form.check_box :admin, id: :user_admin, class: "form-check-input" %>
      <%= form.label :admin, class: "form-check-label" %>
    </div><br>

    <div class="actions" align="center">
      <%= form.submit class: "btn indigo accent-1 mr-3" %>
      <%= link_to '戻る', admin_users_path, class: "btn purple lighten-4" %>
    </div>
  <% end %>
</div>

app/views/admin/users/index.html.erb
<%= javascript_include_tag 'link.js' %>
<div class="container">
  <h5 class="h5-responsive" align="center"><%= t('view.user') %><%= t('view.index') %></h5>
  <div align="right">
    <%= link_to 'ユーザ新規作成', new_admin_user_path, class: "btn indigo accent-1" %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t('view.user_name') %></th>
        <th><%= t('view.email') %></th>
        <th><%= t('view.admin') %></th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr data-link="<%= admin_user_path(user) %>" style="cursor: pointer;">
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= human_boolean(user.admin) %></td>
          <td><%= link_to '編集', edit_admin_user_path(user) %></td>
          <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @users %><br>

  <p class="m-5"></p>

  <div align="center">
    <%= link_to '戻る', admin_index_path, class: "btn purple lighten-4" %>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="container">
  <h5 class="h5-responsive"><%= t('view.user') %>を追加</h5>

  <%= form_with(model: @user, url: admin_users_path, local: true ) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h5 class="h5-responsive"><%= pluralize(@user.errors.count, "つのエラー") %> が存在しているため、保存出来ません:</h5>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :name %>&nbsp;<em><font size="-1">(英数字のみ利用可能です)</font></em>
      <%= form.text_field :name, id: :user_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, id: :user_email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :password %>&nbsp;<em><font size="-1">(6文字以上)</font></em>
      <%= form.password_field :password, id: :user_password, class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :avatar %>
      <% if Rails.env.production? %>
        <%= @user.avatar if @user.avatar && @user.avatar.url %>
      <% else %>
        <%= image_tag(@user.avatar_url) if @user.avatar && @user.avatar.url %>
      <% end %>
      <%= form.file_field :avatar, class: "form-control-file" %>
      <%= form.hidden_field :avatar_cache %>
    </div><br>

    <div class="form-check">
      <%= form.check_box :admin, id: :user_admin, class: "form-check-input" %>
      <%= form.label :admin, class: "form-check-label" %>
    </div>

    <%= form.hidden_field :confirmed_at, :value => Time.now %><br>

    <div class="actions" align="center">
      <%= form.submit class: "btn indigo accent-1 mr-3" %>
      <%= link_to '戻る', admin_users_path, class: "btn purple lighten-4" %>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="col-12">
    <table class="table" width="100%">
      <tr>
        <th><%= t('view.user_name') %></th>
        <td><%= @user.name %></td>
      </tr>
      <tr>
        <th><%= t('view.email') %></th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th><%= t('view.avatar') %></th>
        <td><%= image_tag(@user.avatar.url) if @user.avatar && @user.avatar.url %></td>
      </tr>
      <tr>
        <th><%= t('view.admin') %></th>
        <td><%= human_boolean(@user.admin) %></td>
      </tr>
      <tr>
        <td colspan="2" align="center">
          <%= link_to '編集', edit_admin_user_path(@user), class: "btn indigo accent-1 mr-3" %>
          <%= link_to '戻る', admin_users_path, class: "btn purple lighten-4" %>
        </td>
      </tr>
    </table>
  </div>
</div>